# Generated by Django 6.0.6 on 2026-07-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('email_institucional', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('nivel_acesso', models.CharField(choices=[('recepcionista', 'Recepcionista'), ('coordenacao', 'Coordenação'), ('super_admin', 'Super Admin')], max_length=20)),
                ('usuario_ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'usuário do sistema',
                'verbose_name_plural': 'usuários do sistema',
                'ordering': ('nome_completo',),
            },
        ),
    ]
