# Generated by Django 6.0.6 on 2026-07-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_encaixepaciente_tipoatendimentoencaixe'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosistema',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfis/'),
        ),
    ]
