# Generated by Django 6.0.6 on 2026-07-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_foto_perfil_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='encaixepaciente',
            name='chamado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encaixepaciente',
            name='sala',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='encaixepaciente',
            name='status',
            field=models.CharField(choices=[('validacao', 'Validação'), ('aguardando', 'Aguardando'), ('chamado', 'Chamado'), ('atendimento', 'Em Atendimento'), ('concluido', 'Concluído')], default='validacao', max_length=20),
        ),
    ]
