# Generated by Django 6.0.6 on 2026-07-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_foto_perfil_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosistema',
            name='cargo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usuariosistema',
            name='departamento',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
