# Generated by Django 6.0.6 on 2026-07-26 00:24

from django.db import migrations, models


def normalizar_cpfs(apps, schema_editor):
    UsuarioSistema = apps.get_model("core", "UsuarioSistema")
    # .only("cpf") e proposital (commit cce188a, 28/07/2026): sem isso o
    # iterator() busca a linha inteira, incluindo cargo/departamento -- que
    # em bancos afetados pelo problema da migration 0006 (ver comentario
    # la) ainda nao existiam de verdade, mesmo com a 0006 marcada como
    # aplicada. Buscar so a coluna cpf evita que essa migration quebre
    # nesses bancos.
    for usuario in UsuarioSistema.objects.only("cpf").iterator():
        digits = "".join(ch for ch in (usuario.cpf or "") if ch.isdigit())
        if len(digits) == 11 and digits != usuario.cpf:
            usuario.cpf = digits
            usuario.save(update_fields=["cpf"])


def reverter_cpfs(apps, schema_editor):
    UsuarioSistema = apps.get_model("core", "UsuarioSistema")
    # Mesmo motivo do .only("cpf") em normalizar_cpfs, acima.
    for usuario in UsuarioSistema.objects.only("cpf").iterator():
        d = usuario.cpf
        if d and len(d) == 11 and d.isdigit():
            usuario.cpf = f"{d[0:3]}.{d[3:6]}.{d[6:9]}-{d[9:11]}"
            usuario.save(update_fields=["cpf"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usuariosistema_cargo_usuariosistema_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='nome_mae',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='usuariosistema',
            name='senha_hash',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.RunPython(normalizar_cpfs, reverter_cpfs),
        migrations.AlterField(
            model_name='usuariosistema',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
