# Generated by Django 6.0.6 on 2026-07-26 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_paciente_nome_mae_usuariosistema_senha_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encaixepaciente',
            name='origem',
            field=models.CharField(choices=[('checkin', 'Check-in'), ('encaixe', 'Encaixe')], default='encaixe', max_length=10),
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendamento', models.DateField()),
                ('hora_agendamento', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('checkin_realizado', 'Check-in Realizado'), ('cancelado', 'Cancelado'), ('concluido', 'Concluído')], default='agendado', max_length=20)),
                ('tipo_atendimento', models.CharField(max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='core.paciente')),
            ],
            options={
                'verbose_name': 'agendamento',
                'verbose_name_plural': 'agendamentos',
                'ordering': ('data_agendamento', 'hora_agendamento'),
            },
        ),
    ]
