# Generated by Django 6.0.6 on 2026-07-26 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_encaixepaciente_origem_agendamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ('paciente__nome_completo', 'data_agendamento'), 'verbose_name': 'agendamento', 'verbose_name_plural': 'agendamentos'},
        ),
    ]
