# Generated by Django 6.0.6 on 2026-07-26 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_agendamento_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='encaixepaciente',
            unique_together={('senha', 'data_atendimento')},
        ),
    ]
