# Generated by Django 6.0.6 on 2026-07-27 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_encaixepaciente_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesquisaSatisfacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nome', models.CharField(blank=True, max_length=150)),
                ('paciente_cpf', models.CharField(db_index=True, max_length=14)),
                ('nota', models.PositiveSmallIntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('encaixe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pesquisas_satisfacao', to='core.encaixepaciente')),
            ],
            options={
                'verbose_name': 'pesquisa de satisfação',
                'verbose_name_plural': 'pesquisas de satisfação',
                'ordering': ('-criado_em',),
            },
        ),
    ]
