# Generated by Django 6.0.6 on 2026-07-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_pesquisasatisfacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='encaixepaciente',
            name='ausente_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encaixepaciente',
            name='concluido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encaixepaciente',
            name='vezes_chamado',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='encaixepaciente',
            name='status',
            field=models.CharField(choices=[('validacao', 'Validação'), ('aguardando', 'Aguardando'), ('chamado', 'Chamado'), ('atendimento', 'Em Atendimento'), ('ausente', 'Ausente'), ('concluido', 'Concluído')], default='validacao', max_length=20),
        ),
    ]
