# Generated by Django 6.0.6 on 2026-09-22 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_pesquisasatisfacao_notas_por_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='encaixepaciente',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encaixes', to='core.paciente'),
        ),
        migrations.AddField(
            model_name='pesquisasatisfacao',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pesquisas_satisfacao', to='core.paciente'),
        ),
    ]
