# Generated by Django 6.0.6 on 2026-09-22 14:05
#
# Preenche a FK 'paciente' criada em 0016 a partir do CPF ja gravado em
# EncaixePaciente/PesquisaSatisfacao, para registros existentes. Os campos
# de texto legados (nome_completo, cpf, ... / paciente_nome, paciente_cpf)
# nao sao alterados nem removidos -- essa migracao so preenche a relacao
# nova, sem tocar em dado que o codigo atual ainda le diretamente.

from django.db import migrations


def _apenas_digitos(valor):
    # Copia local (nao importa apps.core_domain.business_rules) porque
    # migracoes de dados nao devem depender de codigo de app que pode
    # mudar/ser removido depois -- Paciente.cpf e sempre gravado so com
    # digitos, mas EncaixePaciente.cpf/PesquisaSatisfacao.paciente_cpf
    # podem vir formatados (000.000.000-00) quando a origem e o encaixe
    # manual da recepcao, cujo formulario nao normaliza o CPF digitado.
    return "".join(ch for ch in (valor or "") if ch.isdigit())


def preencher_fk_paciente(apps, schema_editor):
    Paciente = apps.get_model("core", "Paciente")
    EncaixePaciente = apps.get_model("core", "EncaixePaciente")
    PesquisaSatisfacao = apps.get_model("core", "PesquisaSatisfacao")

    pacientes_por_cpf = {p.cpf: p for p in Paciente.objects.all()}

    encaixes_atualizados = []
    for encaixe in EncaixePaciente.objects.filter(paciente__isnull=True):
        paciente = pacientes_por_cpf.get(_apenas_digitos(encaixe.cpf))
        if paciente is not None:
            encaixe.paciente_id = paciente.id
            encaixes_atualizados.append(encaixe)
    if encaixes_atualizados:
        EncaixePaciente.objects.bulk_update(encaixes_atualizados, ["paciente"])

    pesquisas_atualizadas = []
    for pesquisa in PesquisaSatisfacao.objects.filter(paciente__isnull=True):
        if pesquisa.encaixe_id and pesquisa.encaixe.paciente_id:
            pesquisa.paciente_id = pesquisa.encaixe.paciente_id
            pesquisas_atualizadas.append(pesquisa)
            continue
        paciente = pacientes_por_cpf.get(_apenas_digitos(pesquisa.paciente_cpf))
        if paciente is not None:
            pesquisa.paciente_id = paciente.id
            pesquisas_atualizadas.append(pesquisa)
    if pesquisas_atualizadas:
        PesquisaSatisfacao.objects.bulk_update(pesquisas_atualizadas, ["paciente"])


def reverter(apps, schema_editor):
    # Reverso e um no-op: limpar a FK de volta pra null nao perde dado (os
    # campos de texto legados continuam intactos), so descarta a relacao
    # que essa migracao preencheu.
    EncaixePaciente = apps.get_model("core", "EncaixePaciente")
    PesquisaSatisfacao = apps.get_model("core", "PesquisaSatisfacao")
    EncaixePaciente.objects.update(paciente=None)
    PesquisaSatisfacao.objects.update(paciente=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_adiciona_fk_paciente'),
    ]

    operations = [
        migrations.RunPython(preencher_fk_paciente, reverter),
    ]
