# Generated by Django 6.0.6 on 2026-09-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_backfill_fk_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='tipo_atendimento',
            field=models.CharField(choices=[('consulta', 'Consulta'), ('terapia', 'Terapia'), ('exame_auditivo', 'Exame Auditivo')], max_length=20),
        ),
    ]
